#!/bin/bash

if [ "$1" == "-h" ] ; then
    echo "Usage: GC_calculator <input.fasta> [-h]. Output is #GC, #totalbases, GC%"
    exit 0
fi

if [ "$1" == "--help" ] ; then
    echo "Usage: GC_calculator <input.fasta> [--help] Output is #GC, #totalbases, GC%"
    exit 0
fi


awk ' \
BEGIN { \
    FS=""; \
    cg=0; \
    t=0; \
} \
{ \
    if ($1 != ">") { \
        for (i = 1; i <= NF; i++) { \
            if ($i ~ /[ACTGactg]/) { \
                t++;
            } \
            if ($i ~ /[CGcg]/) { \
                cg++;
            } \
        } \
    } \
} \
END { \
    print (cg/t*100); \
}' $1
